services:
  - type: web
    name: news-telegram-bot
    env: node
    region: frankfurt
    plan: free
    buildCommand: "npm install"
    startCommand: "node bot.js"
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
